name = "oinbox-backend"
main = "backend/src/index.ts"
compatibility_date = "2024-03-20"

[[d1_databases]]
binding = "DB"
database_name = "oconnector-db"
database_id = "ab49a14d-e5d2-434f-9926-964ae69df031"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "oconnector-images"

[ai]
binding = "AI"

[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "oconnector-prod-db"
database_id = "82e58966-1791-4b76-a165-a26f55d5b0f9"

