import { User } from '@shared/types';

export interface ExtendedUser extends User {
  trialEndsAt?: string;
  plan?: string;
}

// === UI SPECIFIC TYPES (Frontend Only) ===

export enum AppView {
  DASHBOARD = 'DASHBOARD',
  INBOX = 'INBOX',
  LISTINGS_FORM = 'LISTINGS_FORM',
  MY_PROPERTIES = 'MY_PROPERTIES',
  MY_CLIENTS = 'MY_CLIENTS',
  MAP = 'MAP',
  CRM = 'CRM',
  CALENDAR = 'CALENDAR',
  SETTINGS = 'SETTINGS',
  AI_CONSULTANT = 'AI_CONSULTANT',
  CALCULATOR = 'CALCULATOR',
  MARKETING = 'MARKETING',
  CAMPAIGNS = 'CAMPAIGNS',
  CONTRACTS = 'CONTRACTS',
  WHATSAPP = 'WHATSAPP',
  // Views do Super Admin
  SUPER_ADMIN_OVERVIEW = 'SUPER_ADMIN_OVERVIEW',
  SUPER_ADMIN_TENANTS = 'SUPER_ADMIN_TENANTS',
  SUPER_ADMIN_FINANCE = 'SUPER_ADMIN_FINANCE',
  // Novas views - Lead Capture Engine
  SUPER_ADMIN_LEADS = 'SUPER_ADMIN_LEADS',
  SUPER_ADMIN_GOOGLE_PLACES = 'SUPER_ADMIN_GOOGLE_PLACES',
  SUPER_ADMIN_QUALIFICATION = 'SUPER_ADMIN_QUALIFICATION',
  SUPER_ADMIN_WHATSAPP_BOT = 'SUPER_ADMIN_WHATSAPP_BOT',
  SUPER_ADMIN_CAMPAIGNS = 'SUPER_ADMIN_CAMPAIGNS',
  SUPER_ADMIN_INBOX = 'SUPER_ADMIN_INBOX',
  SUPER_ADMIN_ANALYTICS = 'SUPER_ADMIN_ANALYTICS',
  SUPER_ADMIN_SETTINGS = 'SUPER_ADMIN_SETTINGS',
  SUPER_ADMIN_USERS = 'SUPER_ADMIN_USERS',
  // Enterprise Features
  SUPER_ADMIN_BUYER_LEADS = 'SUPER_ADMIN_BUYER_LEADS',
  // Tenant Enterprise
  ENTERPRISE_BUYER_LEADS = 'ENTERPRISE_BUYER_LEADS',
  // Legal (Lex AI)
  LEGAL_HUB = 'LEGAL_HUB',
}

export interface ToastNotification {
  id: string;
  type: 'success' | 'error' | 'info' | 'warning';
  message: string;
}
